name: ✨ Feature Request
description: Proponi una nuova funzionalità o un miglioramento per Pleasy
title: "[Features]: "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema o necessità
      description: Descrivi il problema o la frustrazione che questa feature risolverebbe.
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockup / Riferimenti
      description: Se hai mockup, screenshot di riferimento da altri tool, o diagrammi, allegali qui.
      placeholder: "Trascina qui le immagini..."
    validations:
      required: false
