name: ✨ Feature Request
description: Suggest a new feature or improvement for Pleasy
title: "[Features]: "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or need
      description: Describe the problem or frustration this feature would solve.
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / References
      description: If you have mockups, reference screenshots from other tools, or diagrams, attach them here.
      placeholder: "Drag images here..."
    validations:
      required: false
